from google import genai
from google.genai import types

def query_gemini(prompt):
    """
    Sends a prompt to the Gemini model and returns the response.

    Args:
        prompt (str): The input prompt for the model.

    Returns:
        str: The response text generated by the Gemini model.
    """
    client = genai.Client(api_key="AIzaSyCIUinjHF5kk7OibbK6aBV9Hjoum10Q4R8")

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,  # Pass the prompt here
        config=types.GenerateContentConfig(
            thinking_config=types.ThinkingConfig(thinking_budget=0)  # Disables thinking
        ),
    )
    return response.text