import google.generativeai as genai
from google.generativeai import types

def query_gemini(prompt):
    """
    Sends a prompt to the Gemini model and returns the response.

    Args:
        prompt (str): The input prompt for the model.

    Returns:
        str: The response text generated by the Gemini model.
    """
    # Configure the API key directly using genai.configure()
    genai.configure(api_key="AIzaSyCIUinjHF5kk7OibbK6aBV9Hjoum10Q4R8")
    
    # Initialize the model using genai.GenerativeModel()
    model = genai.GenerativeModel(model_name="gemini-2.5-flash") # Use a different model name if needed
    
    # Generate content using the model instance
    response = model.generate_content(
        contents=prompt,
        generation_config=types.GenerationConfig(
            candidate_count=1 # Sets the number of response candidates
        ),
    )
    return response.text