import google.generativeai as genai
from google.generativeai import types
import os
import requests
from dotenv import load_dotenv

load_dotenv()

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
HELICONE_API_KEY = os.getenv("HELICONE_API_KEY")

def query_gemini(prompt):
    """
    Sends a prompt to the Gemini model and returns the response.

    Args:
        prompt (str): The input prompt for the model.

    Returns:
        str: The response text generated by the Gemini model.
    """
    # Configure the API key directly using genai.configure()
    genai.configure(api_key=GEMINI_API_KEY)
    
    # Initialize the model using genai.GenerativeModel()
    model = genai.GenerativeModel(model_name="gemini-2.5-flash") # Use a different model name if needed
    
    # Generate content using the model instance
    response = model.generate_content(
        contents=prompt,
        generation_config=types.GenerationConfig(
            candidate_count=1 # Sets the number of response candidates
        ),
    )
    return response.text

def query_gemini_via_helicone(prompt: str):
    """
    Sends a prompt to the Gemini model via Helicone proxy and returns the response.
    """

    url = "https://google.helicone.ai/v1beta/models/gemini-2.5-flash-lite:generateContent"

    headers = {
        "x-goog-api-key": GEMINI_API_KEY,              # ✅ correct Gemini authentication
        "Helicone-Auth": f"Bearer {HELICONE_API_KEY}", # ✅ still use Bearer for Helicone
        "Content-Type": "application/json",
    }

    data = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ]
    }

    response = requests.post(url, headers=headers, json=data)

    if response.status_code == 200:
        result = response.json()
        return result["candidates"][0]["content"]["parts"][0]["text"]
    else:
        raise ValueError(
            f"Error querying Gemini via Helicone: {response.status_code} - {response.text}"
        )