# llama 3.3-70b-instruct model query connection
import requests
import json

def query_llama(prompt: str, model: str = "meta-llama/llama-3.3-70b-instruct:free") -> str:
    """
    Sends a prompt to the Llama model and returns the response.

    Args:
        prompt (str): The input prompt for the model.
        model (str): The name of the Llama model to query.

    Returns:
        str: The response generated by the Llama model.
    """
    response = requests.post(
        url="https://openrouter.helicone.ai/api/v1/chat/completions",
        headers={
            "Authorization": "Bearer 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",
            "Helicone-Auth": "Bearer sk-helicone-5yb3xiy-2stuvpa-tyzjhai-lkfopqa",
            "Content-Type": "application/json",
        },
        data=json.dumps({
            "model": model,
            "messages": [
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
        })
    )

    if response.status_code == 200:
        return response.json()["choices"][0]["message"]["content"]
    else:
        raise ValueError(f"Error querying Llama model: {response.status_code} - {response.text}")
