# Test for local Ollama model connection
import requests

def query_ollama(prompt, model="phi"):
    """
    Sends a prompt to the specified model and returns the response.

    Args:
        prompt (str): The input prompt for the model.
        model (str): The name of the model to query (default is "mistral").

    Returns:
        str: The response generated by the model.
    """
    url = "http://localhost:11434/api/generate"
    headers = {"Content-Type": "application/json"}

    body = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }

    response = requests.post(url, json=body, headers=headers)
    response.raise_for_status()
    return response.json()["response"]

def test_model_connection():
    """
    Tests whether the phi model is working by sending a sample prompt.

    Returns:
        None
    """
    sample_prompt = "print Hi"
    try:
        response = query_ollama(sample_prompt, model="phi")
        print("Model Response:", response)
    except requests.exceptions.RequestException as e:
        print("Error connecting to the model:", e)

if __name__ == "__main__":
    test_model_connection()