<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net472</TargetFramework>
		<UseWPF>true</UseWPF>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<DebugWith>TUI</DebugWith>
	</PropertyGroup>

	<PropertyGroup>
		<OpenTapPackageDefinitionPath>package.xml</OpenTapPackageDefinitionPath>
		<CreateOpenTapPackage>false</CreateOpenTapPackage>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<CreateOpenTapPackage>true</CreateOpenTapPackage>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3405.78" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="OpenTAP" Version="9.28.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(DebugWith)' == 'TUI' AND '$(Configuration)' == 'Debug'">
		<OpenTapPackageReference Include="TUI" version="1" />
	</ItemGroup>

	<ItemGroup Condition="'$(DebugWith)' == 'Editor' AND '$(Configuration)' == 'Debug'">
		<OpenTapPackageReference Include="Editor" version="9" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Keysight.OpenTap.Wpf">
			<HintPath>..\..\..\..\..\..\..\..\Program Files\OpenTAP\Packages\WPF Controls\Keysight.OpenTap.Wpf.dll</HintPath>
		</Reference>
	</ItemGroup>

	<!-- Post-build step to copy DLLs into OpenTAP plugin folder -->
	<Target Name="CopyToOpenTap" AfterTargets="Build">
		<ItemGroup>
			<MyOutput Include="$(OutputPath)*.dll" />
			<WebView2LoaderDlls Include="$(OutputPath)runtimes\win-x64\native\WebView2Loader.dll" />
			<!-- Above that loader file source need modify -->
		</ItemGroup>

		<!-- Copy managed DLLs -->
		<Copy SourceFiles="@(MyOutput)" DestinationFolder="C:\Program Files\OpenTAP\Packages\KeysightGPT\" />

		<!-- Copy WebView2 native loader -->
		<Copy SourceFiles="@(WebView2LoaderDlls)" DestinationFolder="C:\Program Files\OpenTAP\Packages\KeysightGPT\" SkipUnchangedFiles="true" />
	</Target>
</Project>

