<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<UseWPF>true</UseWPF>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3405.78" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="OpenTAP" Version="9.28.2" />
		<OpenTapPackageReference Include="WPF Controls" Version="9.17.5" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="OpenTap.Plugins.BasicSteps">
			<HintPath>C:\Program Files\OpenTAP\Packages\OpenTAP\OpenTap.Plugins.BasicSteps.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
